#include "bf_cuda_lidar.h"
#include "bf_cuda_voxel.h"
#include "bf_model.h"

#include <cuda_runtime.h>

#include <cmath>
#include <cstdio>
#include <cstdlib>

static const bf_tensor *tensor(const bf_model *m,const char *name){const bf_tensor *t=bf_model_find(m,name);if(!t)std::fprintf(stderr,"missing %s\n",name);return t;}
__global__ static void initialize_points(float *points,size_t count){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<count){size_t voxel=i/2;unsigned x=voxel%1440,y=(voxel/1440)%1440,z=(unsigned)(((voxel*2654435761ull)>>16)%40);points[i*5+0]=-54.0f+(x+0.5f)*0.075f;points[i*5+1]=-54.0f+(y+0.5f)*0.075f;points[i*5+2]=-5.0f+(z+0.5f)*0.2f;points[i*5+3]=((int)(i%31)-15)*0.02f;points[i*5+4]=((int)(i%17)-8)*0.01f;}}
__device__ static unsigned long long hash_mix(unsigned long long x){x^=x>>30;x*=0xbf58476d1ce4e5b9ull;x^=x>>27;x*=0x94d049bb133111ebull;return x^(x>>31);}
__global__ static void hash_dense(const float *data,size_t count,unsigned long long *hash){for(size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;i<count;i+=(size_t)gridDim.x*blockDim.x){unsigned bits=__float_as_uint(data[i]);atomicXor(hash,hash_mix(((unsigned long long)bits<<32)^i));}}
static int compare(const float *device,const bf_tensor *expected){float *actual=(float*)std::malloc(expected->nbytes);if(!actual||cudaMemcpy(actual,device,expected->nbytes,cudaMemcpyDeviceToHost)!=cudaSuccess){std::free(actual);return 0;}const float *reference=(const float*)expected->data;size_t n=expected->nbytes/4;float maximum=0;double mean=0;int ok=1;for(size_t i=0;i<n;++i){float d=std::fabs(actual[i]-reference[i]);maximum=fmaxf(maximum,d);mean+=d;if(!(d<=8e-5f+8e-5f*std::fabs(reference[i])))ok=0;}std::printf("cuda_lidar.output max_abs=%.3g mean_abs=%.3g\n",maximum,mean/n);std::free(actual);return ok;}

int main(int argc,char **argv){if(argc!=3)return 2;char error[256]={0};bf_model *weights=nullptr,*oracle=nullptr;int ok=bf_model_open(argv[1],&weights,error,sizeof(error))&&bf_model_open(argv[2],&oracle,error,sizeof(error));
 const bf_tensor *raw=tensor(oracle,"lidar_backbone.coords"),*feat=tensor(oracle,"lidar_backbone.features"),*expected=tensor(oracle,"lidar_backbone.output");bf_coord4 host[8];const int64_t *r=raw?(const int64_t*)raw->data:nullptr;for(int i=0;i<8&&r;++i)host[i]={(int)r[i*4],(int)r[i*4+1],(int)r[i*4+2],(int)r[i*4+3]};
 bf_cuda_lidar_backbone *small=nullptr;bf_coord4 *dc=nullptr;float *df=nullptr,*out=nullptr;cudaStream_t stream=nullptr;
 if(ok)ok=bf_cuda_lidar_backbone_create(weights,1,41,8,8,3000,&small,error,sizeof(error))&&cudaStreamCreateWithFlags(&stream,cudaStreamNonBlocking)==cudaSuccess&&cudaMalloc(&dc,sizeof(host))==cudaSuccess&&cudaMalloc(&df,8*5*4)==cudaSuccess&&cudaMalloc(&out,expected->nbytes)==cudaSuccess&&cudaMemcpy(dc,host,sizeof(host),cudaMemcpyHostToDevice)==cudaSuccess&&cudaMemcpy(df,feat->data,feat->nbytes,cudaMemcpyHostToDevice)==cudaSuccess&&bf_cuda_lidar_backbone_forward(small,dc,df,8,out,(void*)stream,error,sizeof(error))&&cudaStreamSynchronize(stream)==cudaSuccess&&compare(out,expected);
 cudaFree(out);cudaFree(df);cudaFree(dc);bf_cuda_lidar_backbone_destroy(small);
 const size_t capacity=160000,point_count=100000,dense_count=256ull*180*180;bf_cuda_lidar_backbone *prod=nullptr;bf_cuda_voxelizer *voxelizer=nullptr;bf_coord4 *pc=nullptr;float *pf=nullptr,*pp=nullptr,*bev=nullptr;unsigned *pcount=nullptr;unsigned long long *device_hash=nullptr;bf_voxel_config voxel_config={{-54,-54,-5},{54,54,3},{.075f,.075f,.2f},5,10,capacity};
 if(ok)ok=bf_cuda_lidar_backbone_create(weights,1,41,1440,1440,capacity,&prod,error,sizeof(error))&&bf_cuda_voxelizer_create(&voxel_config,point_count,&voxelizer,error,sizeof(error))&&cudaMalloc(&pp,point_count*5*4)==cudaSuccess&&cudaMalloc(&pc,capacity*sizeof(bf_coord4))==cudaSuccess&&cudaMalloc(&pf,capacity*5*4)==cudaSuccess&&cudaMalloc(&pcount,sizeof(unsigned))==cudaSuccess&&cudaMalloc(&bev,dense_count*4)==cudaSuccess&&cudaMalloc(&device_hash,sizeof(unsigned long long))==cudaSuccess;
 if(ok){initialize_points<<<(point_count+255)/256,256>>>(pp,point_count);ok=cudaDeviceSynchronize()==cudaSuccess;}
 cudaEvent_t begin,end;cudaEventCreate(&begin);cudaEventCreate(&end);float cold=0,warm=0;
 unsigned long long first_hash=0,last_hash=0;float *first_dense=(float*)std::malloc(dense_count*sizeof(float));
 if(ok){cudaEventRecord(begin);ok=bf_cuda_voxelize_mean_f32(voxelizer,pp,point_count,pc,pf,pcount,nullptr,error,sizeof(error))&&bf_cuda_lidar_backbone_forward_count_device(prod,pc,pf,pcount,bev,nullptr,error,sizeof(error));cudaEventRecord(end);cudaEventSynchronize(end);cudaEventElapsedTime(&cold,begin,end);cudaMemset(device_hash,0,sizeof(unsigned long long));hash_dense<<<4096,256>>>(bev,dense_count,device_hash);ok=first_dense&&cudaMemcpy(&first_hash,device_hash,sizeof(first_hash),cudaMemcpyDeviceToHost)==cudaSuccess&&cudaMemcpy(first_dense,bev,dense_count*sizeof(float),cudaMemcpyDeviceToHost)==cudaSuccess;}
 if(ok){cudaEventRecord(begin);for(int i=0;i<3;++i)ok=ok&&bf_cuda_voxelize_mean_f32(voxelizer,pp,point_count,pc,pf,pcount,nullptr,error,sizeof(error))&&bf_cuda_lidar_backbone_forward_count_device(prod,pc,pf,pcount,bev,nullptr,error,sizeof(error));cudaEventRecord(end);cudaEventSynchronize(end);cudaEventElapsedTime(&warm,begin,end);}
 float voxel_warm=0,repeat_max=0;size_t repeat_different=0;if(ok){cudaMemset(device_hash,0,sizeof(unsigned long long));hash_dense<<<4096,256>>>(bev,dense_count,device_hash);float *last_dense=(float*)std::malloc(dense_count*sizeof(float));ok=last_dense&&cudaMemcpy(&last_hash,device_hash,sizeof(last_hash),cudaMemcpyDeviceToHost)==cudaSuccess&&cudaMemcpy(last_dense,bev,dense_count*sizeof(float),cudaMemcpyDeviceToHost)==cudaSuccess;if(ok)for(size_t i=0;i<dense_count;++i){if(first_dense[i]!=last_dense[i])++repeat_different;repeat_max=fmaxf(repeat_max,fabsf(first_dense[i]-last_dense[i]));}std::free(last_dense);if(ok){cudaEventRecord(begin);for(int i=0;i<10;++i)ok=ok&&bf_cuda_voxelize_mean_f32(voxelizer,pp,point_count,pc,pf,pcount,nullptr,error,sizeof(error));cudaEventRecord(end);cudaEventSynchronize(end);cudaEventElapsedTime(&voxel_warm,begin,end);}}
 unsigned voxel_count=0;if(ok)ok=cudaMemcpy(&voxel_count,pcount,sizeof(voxel_count),cudaMemcpyDeviceToHost)==cudaSuccess;
 std::printf("cuda_lidar production points=%zu voxels=%u cold=%.3f ms warm=%.3f ms voxel_warm=%.3f ms repeat_diff=%zu repeat_max=%.3g resident=%.2f MiB boundary=%.2f MiB\n",point_count,voxel_count,cold,warm/3,voxel_warm/10,repeat_different,repeat_max,(bf_cuda_lidar_backbone_resident_bytes(prod)+bf_cuda_voxelizer_resident_bytes(voxelizer))/(1024.0*1024.0),(point_count*5*4+capacity*(sizeof(bf_coord4)+5*4)+sizeof(unsigned)+dense_count*4)/(1024.0*1024.0));
 if(!ok)std::fprintf(stderr,"CUDA LiDAR failure: %s first_hash=%016llx last_hash=%016llx\n",error,first_hash,last_hash);std::free(first_dense);cudaEventDestroy(end);cudaEventDestroy(begin);cudaFree(device_hash);cudaFree(bev);cudaFree(pcount);cudaFree(pf);cudaFree(pc);cudaFree(pp);bf_cuda_voxelizer_destroy(voxelizer);bf_cuda_lidar_backbone_destroy(prod);if(stream)cudaStreamDestroy(stream);bf_model_close(oracle);bf_model_close(weights);return ok?0:5;}
