#include "bf_cuda_runtime.h"

#include "bf_cuda.h"
#include "bf_cuda_bev.h"
#include "bf_cuda_camera.h"
#include "bf_cuda_depth_raster.h"
#include "bf_cuda_lidar.h"
#include "bf_cuda_swin.h"
#include "bf_cuda_transfusion.h"
#include "bf_cuda_voxel.h"
#include "bf_model.h"

#include <cuda_runtime.h>

#include <cstdarg>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>

struct device_outputs {float *center,*height,*dim,*rot,*vel,*heat,*scores;int64_t *labels,*indices;};

struct bf_cuda_runtime {
    size_t point_capacity,voxel_capacity,sparse_capacity,resident_bytes;
    bf_cuda_depth_raster *depth_raster;
    bf_cuda_voxelizer *voxelizer;
    bf_cuda_lidar_backbone *lidar;
    bf_cuda_swin *swin;
    bf_cuda_camera_neck *camera;
    bf_cuda_lss_plan *lss;
    bf_cuda_bev_stage *bev;
    bf_cuda_transfusion *decoder;
    cudaStream_t stream,lidar_stream;cudaEvent_t inputs_ready,lidar_done;
    float *images,*points,*lidar_aug,*lidar_to_image,*image_aug;
    float *camera_rotation,*camera_translation,*intrinsics,*post_rotation,*post_translation,*extra_rotation,*extra_translation,*frustum;
    float *dense_depth,*swin0,*swin1,*swin2,*depth_logits,*context,*full_image_bev,*image_bev;
    bf_coord4 *voxel_coords;float *voxel_features;unsigned *voxel_count;float *lidar_bev,*fusion,*spatial,*shared,*dense_heatmap;
    device_outputs outputs;
    float lss_calibration_cache[210];int lss_calibration_valid;
};

static int fail(char *error,size_t cap,const char *format,...){if(error&&cap){va_list args;va_start(args,format);std::vsnprintf(error,cap,format,args);va_end(args);}return 0;}
static int cuda_ok(cudaError_t status,char *error,size_t cap,const char *where){return status==cudaSuccess?1:fail(error,cap,"%s: %s",where,cudaGetErrorString(status));}

static void free_outputs(device_outputs *o){cudaFree(o->center);cudaFree(o->height);cudaFree(o->dim);cudaFree(o->rot);cudaFree(o->vel);cudaFree(o->heat);cudaFree(o->scores);cudaFree(o->labels);cudaFree(o->indices);}

extern "C" void bf_cuda_runtime_destroy(bf_cuda_runtime *r){if(!r)return;free_outputs(&r->outputs);cudaFree(r->dense_heatmap);cudaFree(r->shared);cudaFree(r->spatial);cudaFree(r->fusion);cudaFree(r->lidar_bev);cudaFree(r->voxel_count);cudaFree(r->voxel_features);cudaFree(r->voxel_coords);cudaFree(r->image_bev);cudaFree(r->full_image_bev);cudaFree(r->context);cudaFree(r->depth_logits);cudaFree(r->swin2);cudaFree(r->swin1);cudaFree(r->swin0);cudaFree(r->dense_depth);cudaFree(r->frustum);cudaFree(r->extra_translation);cudaFree(r->extra_rotation);cudaFree(r->post_translation);cudaFree(r->post_rotation);cudaFree(r->intrinsics);cudaFree(r->camera_translation);cudaFree(r->camera_rotation);cudaFree(r->image_aug);cudaFree(r->lidar_to_image);cudaFree(r->lidar_aug);cudaFree(r->points);cudaFree(r->images);bf_cuda_transfusion_destroy(r->decoder);bf_cuda_bev_stage_destroy(r->bev);bf_cuda_lss_plan_destroy(r->lss);bf_cuda_camera_neck_destroy(r->camera);bf_cuda_swin_destroy(r->swin);bf_cuda_lidar_backbone_destroy(r->lidar);bf_cuda_voxelizer_destroy(r->voxelizer);bf_cuda_depth_raster_destroy(r->depth_raster);if(r->inputs_ready)cudaEventDestroy(r->inputs_ready);if(r->lidar_done)cudaEventDestroy(r->lidar_done);if(r->lidar_stream)cudaStreamDestroy(r->lidar_stream);if(r->stream)cudaStreamDestroy(r->stream);std::free(r);}

static int allocate(void **pointer,size_t bytes,bf_cuda_runtime *r,char *error,size_t cap,const char *name){if(!cuda_ok(cudaMalloc(pointer,bytes),error,cap,name))return 0;r->resident_bytes+=bytes;return 1;}

static int allocate_outputs(device_outputs *o,bf_cuda_runtime *r,char *error,size_t cap){const size_t p=200;return allocate((void**)&o->center,2*p*4,r,error,cap,"allocate CUDA center")&&allocate((void**)&o->height,p*4,r,error,cap,"allocate CUDA height")&&allocate((void**)&o->dim,3*p*4,r,error,cap,"allocate CUDA dimensions")&&allocate((void**)&o->rot,2*p*4,r,error,cap,"allocate CUDA rotation")&&allocate((void**)&o->vel,2*p*4,r,error,cap,"allocate CUDA velocity")&&allocate((void**)&o->heat,10*p*4,r,error,cap,"allocate CUDA query heatmap")&&allocate((void**)&o->scores,10*p*4,r,error,cap,"allocate CUDA query scores")&&allocate((void**)&o->labels,p*8,r,error,cap,"allocate CUDA query labels")&&allocate((void**)&o->indices,p*8,r,error,cap,"allocate CUDA query indices");}

extern "C" int bf_cuda_runtime_create(const char *model_path,size_t point_capacity,size_t voxel_capacity,size_t sparse_capacity,bf_cuda_runtime **out,char *error,size_t cap){if(out)*out=nullptr;if(!model_path||!out||!point_capacity||!voxel_capacity||!sparse_capacity||voxel_capacity>sparse_capacity)return fail(error,cap,"invalid CUDA runtime contract");bf_model *model=nullptr;if(!bf_model_open(model_path,&model,error,cap))return 0;bf_cuda_runtime *r=(bf_cuda_runtime*)std::calloc(1,sizeof(*r));if(!r){bf_model_close(model);return fail(error,cap,"CUDA runtime host allocation failed");}r->point_capacity=point_capacity;r->voxel_capacity=voxel_capacity;r->sparse_capacity=sparse_capacity;bf_voxel_config voxel_cfg={{-54,-54,-5},{54,54,3},{.075f,.075f,.2f},5,10,voxel_capacity};bf_lss_desc lss_desc={1,6,118,32,88,80,{-54,-54,-10},{.3f,.3f,20},{360,360,1}};int ok=cuda_ok(cudaStreamCreateWithFlags(&r->stream,cudaStreamNonBlocking),error,cap,"create CUDA runtime stream")&&bf_cuda_depth_raster_create(point_capacity,6,256,704,&r->depth_raster,error,cap)&&bf_cuda_voxelizer_create(&voxel_cfg,point_capacity,&r->voxelizer,error,cap)&&bf_cuda_lidar_backbone_create(model,1,41,1440,1440,sparse_capacity,&r->lidar,error,cap)&&bf_cuda_swin_create(model,6,256,704,&r->swin,error,cap)&&bf_cuda_camera_neck_create(model,6,32,88,360,360,&r->camera,error,cap)&&bf_cuda_lss_plan_create(&lss_desc,&r->lss,error,cap)&&bf_cuda_bev_stage_create(model,180,180,&r->bev,error,cap)&&bf_cuda_transfusion_create(model,180,180,200,&r->decoder,error,cap);if(!ok)goto failure;
    if(!cuda_ok(cudaStreamCreateWithFlags(&r->lidar_stream,cudaStreamNonBlocking),error,cap,"create CUDA LiDAR stream")||!cuda_ok(cudaEventCreateWithFlags(&r->inputs_ready,cudaEventDisableTiming),error,cap,"create CUDA input event")||!cuda_ok(cudaEventCreateWithFlags(&r->lidar_done,cudaEventDisableTiming),error,cap,"create CUDA LiDAR event"))goto failure;
#define A(P,N,L) if(!allocate((void**)&(P),(N)*sizeof(*(P)),r,error,cap,L))goto failure
    A(r->images,6ull*3*256*704,"allocate CUDA images");A(r->points,point_capacity*5,"allocate CUDA points");A(r->lidar_aug,16,"allocate CUDA lidar augmentation");A(r->lidar_to_image,6*16,"allocate CUDA lidar-to-image");A(r->image_aug,6*16,"allocate CUDA image augmentation");A(r->camera_rotation,6*9,"allocate CUDA camera rotation");A(r->camera_translation,6*3,"allocate CUDA camera translation");A(r->intrinsics,6*9,"allocate CUDA intrinsics");A(r->post_rotation,6*9,"allocate CUDA post rotation");A(r->post_translation,6*3,"allocate CUDA post translation");A(r->extra_rotation,9,"allocate CUDA extra rotation");A(r->extra_translation,3,"allocate CUDA extra translation");A(r->dense_depth,6ull*256*704,"allocate CUDA dense depth");A(r->swin0,6ull*192*32*88,"allocate CUDA Swin stage1");A(r->swin1,6ull*384*16*44,"allocate CUDA Swin stage2");A(r->swin2,6ull*768*8*22,"allocate CUDA Swin stage3");A(r->depth_logits,6ull*118*32*88,"allocate CUDA depth logits");A(r->context,6ull*80*32*88,"allocate CUDA image context");A(r->full_image_bev,80ull*360*360,"allocate CUDA full image BEV");A(r->image_bev,80ull*180*180,"allocate CUDA image BEV");A(r->voxel_coords,voxel_capacity,"allocate CUDA voxel coords");A(r->voxel_features,voxel_capacity*5,"allocate CUDA voxel features");A(r->voxel_count,1,"allocate CUDA voxel count");A(r->lidar_bev,256ull*180*180,"allocate CUDA LiDAR BEV");A(r->fusion,336ull*180*180,"allocate CUDA fusion");A(r->spatial,512ull*180*180,"allocate CUDA spatial feature");A(r->shared,128ull*180*180,"allocate CUDA shared feature");A(r->dense_heatmap,10ull*180*180,"allocate CUDA dense heatmap");
#undef A
    {const bf_tensor *frustum=bf_model_find(model,"vtransform.frustum");if(!frustum||frustum->dtype!=BF_DTYPE_F32||frustum->nbytes!=118ull*32*88*3*4){fail(error,cap,"vtransform.frustum contract mismatch");goto failure;}if(!allocate((void**)&r->frustum,(size_t)frustum->nbytes,r,error,cap,"allocate CUDA frustum")||!cuda_ok(cudaMemcpy(r->frustum,frustum->data,(size_t)frustum->nbytes,cudaMemcpyHostToDevice),error,cap,"upload CUDA frustum"))goto failure;}
    if(!allocate_outputs(&r->outputs,r,error,cap))goto failure;
    r->resident_bytes+=bf_cuda_depth_raster_resident_bytes(r->depth_raster)+bf_cuda_voxelizer_resident_bytes(r->voxelizer)+bf_cuda_lidar_backbone_resident_bytes(r->lidar)+bf_cuda_swin_resident_bytes(r->swin)+bf_cuda_camera_neck_resident_bytes(r->camera)+bf_cuda_lss_plan_resident_bytes(r->lss)+bf_cuda_bev_stage_resident_bytes(r->bev)+bf_cuda_transfusion_resident_bytes(r->decoder);bf_model_close(model);*out=r;return 1;
failure:bf_model_close(model);bf_cuda_runtime_destroy(r);return 0;}

static void extract(const float *matrix,float *rotation,float *translation,size_t count){for(size_t i=0;i<count;++i){const float *m=matrix+i*16;float *q=rotation+i*9;q[0]=m[0];q[1]=m[1];q[2]=m[2];q[3]=m[4];q[4]=m[5];q[5]=m[6];q[6]=m[8];q[7]=m[9];q[8]=m[10];translation[i*3]=m[3];translation[i*3+1]=m[7];translation[i*3+2]=m[11];}}

static int invertible_3x3(const float *m){double determinant=(double)m[0]*(m[4]*m[8]-m[5]*m[7])+(double)m[1]*(m[5]*m[6]-m[3]*m[8])+(double)m[2]*(m[3]*m[7]-m[4]*m[6]);return isfinite(determinant)&&fabs(determinant)>1.17549435e-38;}

__global__ static void concat_bev_kernel(const float *image,const float *lidar,float *fusion){size_t image_count=80ull*180*180,total=336ull*180*180;for(size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;i<total;i+=(size_t)gridDim.x*blockDim.x)fusion[i]=i<image_count?image[i]:lidar[i-image_count];}

static int prepare_lss(bf_cuda_runtime *r,int required,cudaStream_t stream,char *error,size_t cap){return !required||bf_cuda_lss_plan_prepare_calibration_f32(r->lss,r->frustum,r->camera_rotation,r->camera_translation,r->intrinsics,r->post_rotation,r->post_translation,r->extra_rotation,r->extra_translation,(void*)stream,error,cap);}

static int infer_parallel_graph(bf_cuda_runtime *r,size_t point_count,int prepare,
    bf_detections *detections,char *error,size_t cap){cudaStream_t camera=r->stream,lidar=r->lidar_stream;if(!cuda_ok(cudaEventRecord(r->inputs_ready,camera),error,cap,"record CUDA inputs ready")||!cuda_ok(cudaStreamWaitEvent(lidar,r->inputs_ready,0),error,cap,"wait CUDA LiDAR inputs"))return 0;if(!bf_cuda_voxelize_mean_f32(r->voxelizer,r->points,point_count,r->voxel_coords,r->voxel_features,r->voxel_count,(void*)lidar,error,cap)||!bf_cuda_lidar_backbone_forward_count_device(r->lidar,r->voxel_coords,r->voxel_features,r->voxel_count,r->lidar_bev,(void*)lidar,error,cap)||!cuda_ok(cudaEventRecord(r->lidar_done,lidar),error,cap,"record CUDA LiDAR done"))return 0;if(!bf_cuda_depth_rasterize_f32(r->depth_raster,r->points,point_count,r->lidar_aug,r->lidar_to_image,r->image_aug,r->dense_depth,(void*)camera,error,cap)||!bf_cuda_swin_forward(r->swin,r->images,r->swin0,r->swin1,r->swin2,(void*)camera,error,cap)||!bf_cuda_camera_neck_forward(r->camera,r->swin0,r->swin1,r->swin2,r->dense_depth,r->depth_logits,r->context,(void*)camera,error,cap)||!prepare_lss(r,prepare,camera,error,cap)||!bf_cuda_lss_plan_forward_f32(r->lss,r->depth_logits,r->context,r->full_image_bev,(void*)camera,error,cap)||!bf_cuda_camera_downsample_forward(r->camera,r->full_image_bev,r->image_bev,(void*)camera,error,cap)||!cuda_ok(cudaStreamWaitEvent(camera,r->lidar_done,0),error,cap,"join CUDA LiDAR branch"))return 0;concat_bev_kernel<<<4096,256,0,camera>>>(r->image_bev,r->lidar_bev,r->fusion);if(!cuda_ok(cudaGetLastError(),error,cap,"launch CUDA BEV concat")||!bf_cuda_bev_stage_forward(r->bev,r->fusion,r->spatial,r->shared,r->dense_heatmap,(void*)camera,error,cap))return 0;bf_transfusion_raw_outputs raw={r->outputs.center,r->outputs.height,r->outputs.dim,r->outputs.rot,r->outputs.vel,r->outputs.heat,r->outputs.scores,r->outputs.labels,r->outputs.indices};return bf_cuda_transfusion_forward(r->decoder,r->shared,r->dense_heatmap,&raw,(void*)camera,error,cap)&&bf_cuda_transfusion_decode_detections(r->decoder,&raw,0.0f,detections,(void*)camera,error,cap);}

static int infer_serial_graph(bf_cuda_runtime *r,size_t point_count,int prepare,bf_detections *detections,char *error,size_t cap){cudaStream_t s=r->stream;if(!bf_cuda_depth_rasterize_f32(r->depth_raster,r->points,point_count,r->lidar_aug,r->lidar_to_image,r->image_aug,r->dense_depth,(void*)s,error,cap)||!bf_cuda_voxelize_mean_f32(r->voxelizer,r->points,point_count,r->voxel_coords,r->voxel_features,r->voxel_count,(void*)s,error,cap)||!bf_cuda_lidar_backbone_forward_count_device(r->lidar,r->voxel_coords,r->voxel_features,r->voxel_count,r->lidar_bev,(void*)s,error,cap)||!bf_cuda_swin_forward(r->swin,r->images,r->swin0,r->swin1,r->swin2,(void*)s,error,cap)||!bf_cuda_camera_neck_forward(r->camera,r->swin0,r->swin1,r->swin2,r->dense_depth,r->depth_logits,r->context,(void*)s,error,cap)||!prepare_lss(r,prepare,s,error,cap)||!bf_cuda_lss_plan_forward_f32(r->lss,r->depth_logits,r->context,r->full_image_bev,(void*)s,error,cap)||!bf_cuda_camera_downsample_forward(r->camera,r->full_image_bev,r->image_bev,(void*)s,error,cap))return 0;concat_bev_kernel<<<4096,256,0,s>>>(r->image_bev,r->lidar_bev,r->fusion);if(!cuda_ok(cudaGetLastError(),error,cap,"launch CUDA BEV concat"))return 0;if(!bf_cuda_bev_stage_forward(r->bev,r->fusion,r->spatial,r->shared,r->dense_heatmap,(void*)s,error,cap))return 0;bf_transfusion_raw_outputs raw={r->outputs.center,r->outputs.height,r->outputs.dim,r->outputs.rot,r->outputs.vel,r->outputs.heat,r->outputs.scores,r->outputs.labels,r->outputs.indices};return bf_cuda_transfusion_forward(r->decoder,r->shared,r->dense_heatmap,&raw,(void*)s,error,cap)&&bf_cuda_transfusion_decode_detections(r->decoder,&raw,0.0f,detections,(void*)s,error,cap);}

extern "C" int bf_cuda_runtime_infer(bf_cuda_runtime *r,const bf_frame_input *frame,bf_detections *detections,char *error,size_t cap){if(!r||!frame||!detections||!frame->camera_images||!frame->points||!frame->camera_intrinsics_6x16||!frame->camera_to_lidar_6x16||!frame->image_augmentation_6x16||!frame->lidar_augmentation_16||!frame->lidar_to_image_6x16||!frame->point_count||frame->point_count>r->point_capacity)return fail(error,cap,"invalid CUDA runtime frame");float cr[54],ct[18],intr[54],unused[18],pr[54],pt[18],er[9],et[3];extract(frame->camera_to_lidar_6x16,cr,ct,6);extract(frame->camera_intrinsics_6x16,intr,unused,6);extract(frame->image_augmentation_6x16,pr,pt,6);extract(frame->lidar_augmentation_16,er,et,1);cudaStream_t s=r->stream;
    if(!invertible_3x3(er))return fail(error,cap,"singular CUDA lidar augmentation");for(int camera=0;camera<6;++camera)if(!invertible_3x3(intr+camera*9)||!invertible_3x3(pr+camera*9))return fail(error,cap,"singular CUDA camera calibration %d",camera);
#define COPY(D,S,N,L) if(!cuda_ok(cudaMemcpyAsync(D,S,(N)*sizeof(*(D)),cudaMemcpyHostToDevice,s),error,cap,L))return 0
    COPY(r->images,frame->camera_images,6ull*3*256*704,"upload CUDA images");COPY(r->points,frame->points,frame->point_count*5,"upload CUDA points");COPY(r->lidar_aug,frame->lidar_augmentation_16,16,"upload CUDA lidar augmentation");COPY(r->lidar_to_image,frame->lidar_to_image_6x16,6*16,"upload CUDA lidar-to-image");COPY(r->image_aug,frame->image_augmentation_6x16,6*16,"upload CUDA image augmentation");COPY(r->camera_rotation,cr,54,"upload CUDA camera rotation");COPY(r->camera_translation,ct,18,"upload CUDA camera translation");COPY(r->intrinsics,intr,54,"upload CUDA intrinsics");COPY(r->post_rotation,pr,54,"upload CUDA post rotation");COPY(r->post_translation,pt,18,"upload CUDA post translation");COPY(r->extra_rotation,er,9,"upload CUDA extra rotation");COPY(r->extra_translation,et,3,"upload CUDA extra translation");
#undef COPY
    float key[210];float *cursor=key;
#define PACK(P,N) do{std::memcpy(cursor,(P),(N)*sizeof(float));cursor+=(N);}while(0)
    PACK(cr,54);PACK(ct,18);PACK(intr,54);PACK(pr,54);PACK(pt,18);PACK(er,9);PACK(et,3);
#undef PACK
    int changed=std::getenv("BF_CUDA_LSS_REBUILD_PLAN")||!r->lss_calibration_valid||
        std::memcmp(key,r->lss_calibration_cache,sizeof(key))!=0;
    int ok=std::getenv("BF_CUDA_RUNTIME_PARALLEL")?infer_parallel_graph(r,frame->point_count,changed,detections,error,cap):infer_serial_graph(r,frame->point_count,changed,detections,error,cap);
    if(ok&&changed){std::memcpy(r->lss_calibration_cache,key,sizeof(key));r->lss_calibration_valid=1;}return ok;}

extern "C" size_t bf_cuda_runtime_resident_bytes(const bf_cuda_runtime *r){return r?r->resident_bytes:0;}

__global__ static void bev_stats_kernel(const float *data,size_t count,float *sum,float *maximum){__shared__ float sums[256],maxima[256];float local_sum=0,local_max=0;for(size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;i<count;i+=(size_t)gridDim.x*blockDim.x){float value=fabsf(data[i]);local_sum+=value;local_max=fmaxf(local_max,value);}sums[threadIdx.x]=local_sum;maxima[threadIdx.x]=local_max;__syncthreads();for(int step=128;step;step>>=1){if(threadIdx.x<step){sums[threadIdx.x]+=sums[threadIdx.x+step];maxima[threadIdx.x]=fmaxf(maxima[threadIdx.x],maxima[threadIdx.x+step]);}__syncthreads();}if(!threadIdx.x){atomicAdd(sum,sums[0]);atomicMax((unsigned*)maximum,__float_as_uint(maxima[0]));}}

extern "C" int bf_cuda_runtime_debug_bev_stats(const bf_cuda_runtime *r,float stats[4],char *error,size_t cap){if(!r||!stats)return fail(error,cap,"invalid CUDA BEV stats contract");float *device=nullptr;if(!cuda_ok(cudaMalloc(&device,4*sizeof(float)),error,cap,"allocate CUDA BEV stats"))return 0;cudaMemset(device,0,4*sizeof(float));bev_stats_kernel<<<4096,256>>>(r->image_bev,80ull*180*180,device,device+1);bev_stats_kernel<<<4096,256>>>(r->lidar_bev,256ull*180*180,device+2,device+3);int ok=cuda_ok(cudaGetLastError(),error,cap,"launch CUDA BEV stats")&&cuda_ok(cudaMemcpy(stats,device,4*sizeof(float),cudaMemcpyDeviceToHost),error,cap,"copy CUDA BEV stats");cudaFree(device);return ok;}

__device__ static unsigned long long debug_mix(unsigned long long value){value^=value>>30;value*=0xbf58476d1ce4e5b9ull;value^=value>>27;value*=0x94d049bb133111ebull;return value^(value>>31);}
__global__ static void tensor_hash_kernel(const float *data,size_t count,unsigned long long *hash){unsigned long long local=0;for(size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;i<count;i+=(size_t)gridDim.x*blockDim.x)local^=debug_mix((i<<32)^__float_as_uint(data[i]));if(local)atomicXor(hash,local);}
extern "C" int bf_cuda_runtime_debug_hashes(const bf_cuda_runtime *r,unsigned long long hashes[11],char *error,size_t cap){if(!r||!hashes)return fail(error,cap,"invalid CUDA hash contract");unsigned long long *device=nullptr;if(!cuda_ok(cudaMalloc(&device,11*sizeof(*device)),error,cap,"allocate CUDA hashes")||!cuda_ok(cudaMemset(device,0,11*sizeof(*device)),error,cap,"clear CUDA hashes")){cudaFree(device);return 0;}const float *data[11]={r->dense_depth,r->swin0,r->swin1,r->swin2,r->depth_logits,r->context,r->full_image_bev,r->image_bev,r->lidar_bev,r->shared,r->dense_heatmap};const size_t counts[11]={6ull*256*704,6ull*192*32*88,6ull*384*16*44,6ull*768*8*22,6ull*118*32*88,6ull*80*32*88,80ull*360*360,80ull*180*180,256ull*180*180,128ull*180*180,10ull*180*180};for(int i=0;i<11;++i)tensor_hash_kernel<<<4096,256>>>(data[i],counts[i],device+i);int ok=cuda_ok(cudaGetLastError(),error,cap,"launch CUDA tensor hashes")&&cuda_ok(cudaMemcpy(hashes,device,11*sizeof(*hashes),cudaMemcpyDeviceToHost),error,cap,"copy CUDA tensor hashes");cudaFree(device);return ok;}
